Task : FAISS
Experiment : LLM-Science
seed : 42
data: 
    train_path : /home/jisukim/LLMscience/dataset/train.csv
    valid_path : /home/jisukim/LLMscience/dataset/valid.csv
    wiki_path : /home/jisukim/LLMscience/openbook/dataset/stem_wiki.csv
    batch_size: 32
    faiss_output_path: /home/jisukim/LLMscience/openbook/stem_faiss/faiss/bge-base-en-v1.5-index.index

model:
    model_name: BAAI/bge-base-en-v1.5
    device: cuda:1
    word_embedding_dimension: 768
