Task : LLM
Experiment : LLM-Science
seed : 42
data: 
    train : /home/jisukim/LLMscience/dataset/all_12_with_context2.csv
    # valid: /home/jisukim/LLMscience/dataset/valid.csv
    batch_size: 2
    max_length: 512
model:
    device: cuda:1
    model_name: microsoft/deberta-v3-large
    epoch: 5
    accumulation_steps: 4
    
